### ISSUE TITLE
Dotnet Core support?

### ISSUE THREAD

**Issue by hashhar** [AlexPoint/OpenNlp#12]
Is it possible to port this to Dotnet Core?

**Comment by hashhar** [comment]
I am trying to do so. Could you please give an overview as to what Projects within the solution do what?

@AlexPoint

**Comment by AlexPoint** [comment]
I haven't ported any project to Dotnet Core yet so I really cannot say whether that's doable or not.
I'd try porting the OpenNlp project first, since it's he main project in this solution (the one with the actual NLP intelligence).
The other projects are here either for factoring some general purpose code or testing.
Let me know if that helped.

**Comment by hashhar** [comment]
Thanks. I was able to port the OpenNLP and Entropy projects but both of them lost the System.Runtime.Caching advantages since Core doesn't have that API yet. I'll keep and report back to you once I manage to make it as performant as the native version.

**Comment by paulcarroll** [comment]
Hi @hashhar, how are you going with the core port? What fork are you working in? I'll be happy to jump in and give feedback/input if you want... really need this going myself!  :)

**Comment by hashhar** [comment]
@paulcarroll I actually tried to get it to just build. Ended up stripping around everything. But I don't this is feasible right now because System.Caching is not available and that hurt the performance a lot. Too much.

You can start on a fork but I don't think it'll help much right now.

**Comment by AlexPoint** [comment]
@paulcarroll @hashhar : indeed, the caching mecanism is important for performance reasons.
It seems that some caching mecanism is possible with dotnet core (see https://wildermuth.com/2016/04/14/Using-Cache-in-ASP-NET-Core-1-0-RC1). I haven't used it myself but that could be a good place to start.
Let me know if I can help somehow.

**Comment by paulcarroll** [comment]
@AlexPoint thanks mate, will do

**Comment by hashhar** [comment]
Thanks for the info @AlexPoint. I'll try to contribute after my exams end at the end of this month.

**Comment by kostyrin** [comment]
@AlexPoint I' ve finished porting the project to .Net Core.
link [there](https://github.com/kostyrin/OpenNLP.Standard)
There are  OpenNLP, SharpEntropy, SharpWordNet projects.
Because I need it for my project.
I think it will be helpful.

**Comment by AlexPoint** [comment]
The port looks good.
If you want, you can do a pull request and I'll reintegrate your changes in the main version.
