### ISSUE TITLE
What version of OpenNLP is this?

### ISSUE THREAD

**Issue by robmuld** [AlexPoint/OpenNlp#13]
Is this a port of v1.3.4 of OpenNLP? Or is 1.3.4 the version of this project itself

**Comment by AlexPoint** [comment]
It's v1.3.4 of the nuget package (hence of the project itself).

**Comment by robmuld** [comment]
Thanks. And which version of OpenNLP is it then?

**Comment by AlexPoint** [comment]
It was based initially on https://sharpnlp.codeplex.com/, which itself was based on https://github.com/apache/opennlp (v1.5.2).
This version has slightly diverged after that though.

**Comment by robmuld** [comment]
Thanks for the info
