### ISSUE TITLE
Sentence splitting not splitting as expected

### ISSUE THREAD

**Issue by emmagarland** [AlexPoint/OpenNlp#22]
Hi, I'm finding some behaviour with the default model and the SentenceDetect method, using the EnglishMaximumEntropySentenceDetector.

My first input is:

- _This is a sentence without spaces.Should be split into three?Is not?_

I would expect a list of strings like:

- "This is a sentence without spaces."
- "Should be split into three?"
- "Is not?"

The results come out as:

- "This is a sentence without spaces.Should"
- "be split into three.It is split in the wrong places."

Same for a sentence without many spaces:

- _This is a sentence without spaces.Should be split into three.It is split in the wrong places._

I would expect a list of strings like:

- "This is a sentence without spaces.",
- "Should be split into three.",
- "It is split in the wrong places."

The results come out as:

- "This is a sentence without spaces.Should"
- "be split into three?Why"
- "not?"

The sentence finds the end positions with the characters (33, 60 and 68 for the first example), but the FirstWhiteSpace method finds 40 as there are no white spaces after the punctuation as you would expect.

Is there something I am missing that I need to specify or train for this to work? Or do I have to sanitise the input first by making sure any special character has a space after it? 

If I change the input to _"This is a sentence without spaces. Should be split into three? Is not?"_ then it works and splits as expected.

Thanks!
Emma

**Comment by AlexPoint** [comment]
The model has been trained on examples for which the spaces after the end of a sentence (., !, ?) were (in general) respected. 
Hence the fact that it's optimized to detect end of sentences when this condition has been met.

If you want, you can train your own model with multiple examples as the ones above and this new model will be more accurate in this case. However, be aware that there will be some edge cases as well. One that comes to my mind immediately are the acronyms with punctuation (eg U.S., K.G.B...).
It's likely that your new model will split sentences on those acronyms as well.

**Comment by emmagarland** [comment]
OK, that makes sense @AlexPoint  - I have been trying to handle this via preparsing and adding a space at the end of a sentence, but as you say acronyms with punctuations & decimals become really problematic then. I ended up with a horribly long regex to try and improve it, hopefully sentences constructed in this way won't be a common problem for us more like an edge case. Best, and thanks for the detailed reply. Emma

**Comment by AlexPoint** [comment]
Indeed, the first - and easiest option - is to treat those cases as edge cases (a correct sentence separator should have a space right after) if they are indeed rare.

Another option that you can investigate is to train your own model like I said above and create your own [SentenceDetectionContextSeparator](https://github.com/AlexPoint/OpenNlp/blob/master/OpenNLP/Tools/SentenceDetect/SentenceDetectionContextGenerator.cs). As you mentioned, acronyms and numbers with decimals are the cases which could collide with the badly written sentences. In this SentenceDetectonContextGenerator, we are building a collectFeatures list; look at the features we are computing to compute the probability of being an end of sentence. 
It can probably be enriched with more features that would improve the detection on the cases listed above. The few that comes to my mind right now are:
- the length of the prefix/suffix (" X.Y " in general will be an acronym and not an end of sentence whereas " XYZ.ABZ" is likely the opposite)
- whether the prefix/suffix can be parsed as a number (" 123.456 " in general will not be an end of sentence whereas " XYZ.ABC " is likely the opposite)
- whether the whole prefix/suffix is uppercase
- ...
You will have to spend some time building the training set and refining the logic though. So make sure it's worth it ;)

I hope that is clear enough and good luck.

**Comment by emmagarland** [comment]
@AlexPoint great and clear explanation, many thanks. When I get back to working on this project I will revisit and I'll update you if I manage to enrich the sentence detection based on the various conditions we have discussed. I think it will be worth the effort.

Thanks again 👍 

Emma

**Comment by Wardlegrant** [comment]
I am having the same issue as Emma. The model appears to be working correctly, as it is picking up the end of the sentence, it is just adding an extra word too it. After doing some testing it looks like it is related to line 214  method SentencePositionDetect in the MaximumEntropySentenceDectector class, It is looking for a white space before it starts to look for the next Char, hence adding on the first word of the next sentence. If you remove that clause it appears to work fine.

Thanks
Grant

**Comment by emmagarland** [comment]
@Wardlegrant interesting find - I didn't get around to training my own model for this, but sounds like it can perhaps be resolved in this code amend. I will see if I can make some time to replicate this and if it resolves the scenarios I found before.
