### ISSUE TITLE
Using other languages' models with this port

### ISSUE THREAD

**Issue by njfm0001** [AlexPoint/OpenNlp#25]
I would like to know how to use bin files from the [OpenNLP official site](http://opennlp.sourceforge.net/models-1.5/) to make it work with this port.

**Comment by AlexPoint** [comment]
To use the bin files for other languages, you should use the generic classes (or create specific classes for a given language) and pass the appropriate bin files to the constructor.
For instance, for sentence detection:

var modelPath = "path/to/de-sent.bin";
var sentenceDetector = new MaximumEntropySentenceDetector(new SharpEntropy.GisModel(new SharpEntropy.IO.BinaryGisModelReader(modelPath)));
var sentences = sentenceDetector.SentenceDetect(paragraph);
