### ISSUE TITLE
What is the LICENSE for OpenNLP?

### ISSUE THREAD

**Issue by srayuws** [AlexPoint/OpenNlp#5]
Hi Alex,

I am a developer who wants to use the OpenNLP in one of my projects, but cannot find any LICENSE file in the project. 

Can you kindly tell me which license it is using now? Or add a license file to the project so that other users can also distribute their software in a correct way.

And maybe a useful link here, to make the decision easier: http://choosealicense.com/ 

Thanks

**Comment by fleex** [comment]
My mistake for forgetting the license.
It's now fixed (GPL, see https://github.com/AlexPoint/OpenNlp/blob/master/LICENSE)

**Comment by AlexPoint** [comment]
My mistake for forgetting the license.
It's now fixed (GPL, see https://github.com/AlexPoint/OpenNlp/blob/master/LICENSE)
